### ISSUE TITLE
key-error

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#11]
первый запуск.

![ff](https://cloud.githubusercontent.com/assets/4154978/14475505/5dd70100-0113-11e6-8965-ae22bd634c4f.png)

```
[ 0.01"]collect_files:687 >>1(:)how_walk={'root': '/home/user/lazarus/examples', 'skip_binr': False, 'file_excl': '', 'depth': -1, 'skip_hidn': False, 'sort_type': '', 'only_frst': 0, 'file_incl': '*.pp'}
[ 0.03"]    collect_files:714 incls=['*.pp']
[ 0.04"]    collect_files:715 excls=[]
[ 0.23"]    1(:)=[ 0.20"]
[ 0.24"]find_in_files:569 #files=35
[ 0.25"]find_in_files:591 ?? files (==[ 0.00"]
[ 0.29"]find_in_files:671 ok files ==)[ 0.05"] #rsp_l=3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_find_in_files/cd_fi_in_fi.py", line 431, in show_dlg
    if '1'==vals['toed']:
KeyError: 'toed'
```

**Comment by kvichans** [comment]
Ясно 
Мне - ToDo
Вам пока пользоваться в more-режиме

**Comment by kvichans** [comment]
fix
