### ISSUE TITLE
err in Options editor

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#122]
On call option editor
```
Python 3.5.2
Loading icons: LibreOffice_24x24
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_find_in_files/__init__.py", line 23, in dlg_fif_opts
    def dlg_fif_opts(self):                 return RLS.dlg_fif_opts()
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 238, in dlg_fif_opts
    return dlg_fif_opts()
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 243, in dlg_fif_opts
    fif_opts    = json.loads(open(FIF_OPTS).read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 3124: invalid start byte
```

user.json
```
{
  "ui_font_name" : "Sans",
  "ui_font_size" : 16,
  "ui_font_name__linux" : "Sans",
  "ui_font_size__linux" : 10,
  "font_name__linux" : "Ubuntu Mono",
  "font_size__linux" : 11,
  "tab_size" : 4,
    "numbers_show": true,
  "margin" : 2000,
  "caret_after_end" : true,
  "caret_shape": 2,
  "undo_grouped" : false,
  "ui_reopen_session" : false,
  "ui_listbox_fuzzy" : false,
  "spacing_y" : 1,
  "config_menus_1st_done" : true,
  "unprinted_replace_spec" : false,
  "show_cur_line" : false,
  "fif_fold_prev_res" : true,
  "fif_skip_file_size_more_Kb" : 2000,
  "find_sel_case" : 1,
  "comment_equal_column" : true,
  "find_separate_form" : false,
  "find_suggest_cur_word" : true,
  "pylib__linux" : "libpython3.5m.so.1.0",
  "auto_close_brackets" : "",
  "palette_more" : true,
  "last_palette_type" : "60 colors: 3*20",
  "active_palettes" : "60 colors: 3*20|142 colors: 7-hexagon|216 web-colors: 9-hexagon|3221 colors: 7-hexagon, dialog|146 named colors",
  "last_palette_grey_level" : 2960685,
  "ui_tab_size_y": 25,
    "font_name": "default",
    "numbers_style": 2,
}
```

**Comment by kvichans** [comment]
А этот файл у вас в utf-8 ?

**Comment by Alexey-T** [comment]
Да

**Comment by kvichans** [comment]
Это сбой не на user.json, а на новом файле из папки ФИФ
Действительно он у меня был не в utf-8
