### ISSUE TITLE
Cannot open options ed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#140]
View/edit options-
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Cudatext\py\cuda_find_in_files\__init__.py", line 23, in dlg_fif_opts
    def dlg_fif_opts(self):                 return RLS.dlg_fif_opts()
  File "C:\Cudatext\py\cuda_find_in_files\cd_fi_in_fi.py", line 238, in dlg_fif_opts
    return dlg_fif_opts()
  File "C:\Cudatext\py\cuda_find_in_files\cd_fi_in_fi.py", line 244, in dlg_fif_opts
    from cuda_options_editor import dlg_opt_editor
ImportError: No module named 'cuda_options_editor'
```

**Comment by kvichans** [comment]
ToDo
