### ISSUE TITLE
TypeError on opening

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#142]
1.4.01
при открытии длг.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_find_in_files/__init__.py", line 4, in show_dlg
    def show_dlg(self, what='', opts={}):   return RLS.show_dlg(what, opts)
  File "/home/user/cuda/cuda/app/py/cuda_find_in_files/cd_fi_in_fi.py", line 125, in show_dlg
    return dlg_fif(what, opts)
  File "/home/user/cuda/cuda/app/py/cuda_find_in_files/cd_fi_in_fi.py", line 1540, in dlg_fif
    dlg_agent(fif_dlg_loop, *fif_pars_for_agent('start')) ##!!
  File "/home/user/cuda/cuda/app/py/cuda_find_in_files/cd_plug_lib.py", line 979, in dlg_agent
    app.dlg_proc(           idDlg, app.DLG_SHOW_MODAL)
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 620, in dlg_proc
    _dlg_proc_wait(id_dialog)
  File "/home/user/cuda/cuda/app/py/cudatext.py", line 613, in _dlg_proc_wait
    if not d['vis']:
TypeError: 'frame' object is not subscriptable
```

**Comment by Alexey-T** [comment]
ошибка у меня. Поправил в cudatext.py
