### ISSUE TITLE
adjust: down btn err

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#144]
Нажатие стрелок у spinedit

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 602, in _dlg_agent_callback
    agent_callback(id_dlg, id_ctl_act, id_event, info)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 965, in agent_loop
    settings    = client_data_updater(fm_aid, fm_vals, fm_fid, fm_chds)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by kvichans** [comment]
Повторил
