### ISSUE TITLE
Crash on Esc after long search

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#173]
- ищу строку в папке лазаруса - долго, больше 10с- окно ФИФ видно
- не дождался, надал Esc-- закрылось окно но поиск идет- статусбар показывает что идет
- еще раз Esc
```
Python 3.5.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cudatext.py", line 751, in _dlg_proc_callback_proxy
    _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 1232, in da_c_callbk
    upds    = user_callbk(cid, self)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 1607, in do_work
    return self.do_focus(aid,ag)   #continue#while_fif
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 1097, in do_focus
    fid     = ag.fattr('focused')
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 682, in fattr
    rsp = app.dlg_proc(self.id_dlg, app.DLG_CTL_PROP_GET, index=rsp)['name']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kvichans** [comment]
Да. Сам это уже видел. Нужно придумать новый способ - старый 'перехват ESC" не работает

**Comment by Alexey-T** [comment]
тут можно просто проверять ответ res=dlg_proc(), и не делать res[index].

**Comment by kvichans** [comment]
Нет, не "просто"

**Comment by Alexey-T** [comment]
вам виднее.
