### ISSUE TITLE
Crash on input

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#250]
```
Startup: total: 390ms, including plugins: 0ms
Python 3.7.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cudatext.py", line 1046, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 1688, in da_c_callbk
    upds    = u_callbk(cid, self, data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 2060, in do_work
    if root_is_proj(self.fold_s) or root_is_tabs(self.fold_s):
  File "/home/user/.config/cudatext/py/cuda_find_in_files/cd_fif_api.py", line 55, in <lambda>
    root_is_proj    = lambda rt:    (rt[:2]+rt[-1]).upper() in ('<P>')
IndexError: string index out of range
```

вводил
![Screenshot from 2019-12-26 16-44-32](https://user-images.githubusercontent.com/4154978/71478175-4706e780-27ff-11ea-871b-b7d6ac9146cd.png)

**Comment by Alexey-T** [comment]
@kvichans  ?

**Comment by kvichans** [comment]
Не проявляется

**Comment by Alexey-T** [comment]
root_is_proj    = lambda rt:    (rt[:2]+rt[-1]).upper() in ('<P>')

это падает.
вы можете заменить это на обыч.фцнкцию, которая сделает поверку на индекс (если len(rt)<3, то вернуть False)

**Comment by kvichans** [comment]
Сори, действительно пропустил проверку обязательного поля на пустоту.
ToDo

**Comment by kvichans** [comment]
Чуть подожду результатов расследования `set_carets` и опубликую.

**Comment by Alexey-T** [comment]
я не имею репро (с таймером) и не знаю что еще искать.
