### ISSUE TITLE
crash on Ctrl+click on = button

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#254]
macOS, 
```
Python 3.7
Init: cuda_config_toolbar
Loaded session: "history session.json", 0ms, 0 file(s)
Startup: 770ms, plugins: 150ms (config_toolbar 151ms)
Init: cuda_addonman
Init: cuda_find_in_files
Init: cudatext
Traceback (most recent call last):
  File "/Users/teacher/Library/Application Support/CudaText/py/cudatext.py", line 1112, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_plug_lib.py", line 1688, in da_c_callbk
    upds    = u_callbk(cid, self, data)
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_fi_in_fi.py", line 2454, in do_menu
    dlg_valign_consts()
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_plug_lib.py", line 2199, in dlg_valign_consts
    ,('save',dict(tp='bt'    ,t=DLG_H-30         ,l=115  ,w=100  ,cap=_('&Save')     ,call=lambda cid,ag,d: save()
NameError: name '_' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/__init__.py", line 4, in show_dlg
    def show_dlg(self, what='', opts={}):   return RLS.show_dlg(what, opts)
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_fi_in_fi.py", line 153, in show_dlg
    return dlg_fif(what, opts)
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_fi_in_fi.py", line 1239, in dlg_fif
    return FifD(what, opts).show()
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_fi_in_fi.py", line 1378, in show
    self.ag.show(callbk_on_exit=lambda ag: self.do_exit('', ag))
  File "/Users/teacher/Library/Application Support/CudaText/py/cuda_find_in_files/cd_plug_lib.py", line 913, in show
    app.dlg_proc(self.id_dlg, app.DLG_SHOW_MODAL)
  File "/Users/teacher/Library/Application Support/CudaText/py/cudatext.py", line 1140, in dlg_proc
    _dlg_proc_wait(id_dialog)
  File "/Users/teacher/Library/Application Support/CudaText/py/cudatext.py", line 1100, in _dlg_proc_wait
    app_idle()
  File "/Users/teacher/Library/Application Support/CudaText/py/cudatext.py", line 887, in app_idle
    return ct.app_idle(wait)
SystemError: <built-in function app_idle> returned a result with an error set
```

**Comment by kvichans** [comment]
Да, вижу. ToDo

**Comment by kvichans** [comment]
Опубликовал
