### ISSUE TITLE
_ not defined

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#255]
ctrl+click on = btn.
linux
```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cudatext.py", line 1112, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 1688, in da_c_callbk
    upds    = u_callbk(cid, self, data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 2454, in do_menu
    dlg_valign_consts()
  File "/home/user/.config/cudatext/py/cuda_find_in_files/cd_plug_lib.py", line 2199, in dlg_valign_consts
    ,('save',dict(tp='bt'    ,t=DLG_H-30         ,l=115  ,w=100  ,cap=_('&Save')     ,call=lambda cid,ag,d: save()
NameError: name '_' is not defined
```

**Comment by kvichans** [comment]
Да, уже поправил и опубликовал

**Comment by Alexey-T** [comment]
и все равно етот баг есть.

**Comment by kvichans** [comment]
ДА! Поправил баг, пока делал зип - отвлекся на другие мелочи и ЗАБЫЛ скопировать.
Выложил правильный зип. Сори
