### ISSUE TITLE
err, dir /

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#42]
```
Python 3.4.3 (default, Oct 14 2015, 20:31:36) 
[GCC 4.8.4]
Setting icons: AwOken_24x24
[ 0.02"]collect_files:1633 >>1(:)how_walk={'file_incl': '*', 'depth': -1, 'root': '', 'only_frst': 0, 'sort_type': '', 'enco': ['cp1252', 'UTF-8', '"detected"'], 'skip_binr': True, 'file_excl': '', 'skip_hidn': True}
[ 0.40"]    1(:)=[ 0.00"]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_find_in_files/__init__.py", line 4, in show_dlg
    def show_dlg(self, what='', opts={}):   return RLS.show_dlg(what, opts)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 112, in show_dlg
    return dlg_fif(what, opts)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 807, in dlg_fif
    ,progressor = progressor
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 1373, in find_in_files
    collect_files(how_walk, progressor)
ValueError: need more than 0 values to unpack
```

findin
![ff](https://cloud.githubusercontent.com/assets/4154978/15161171/2edf5350-170e-11e6-9c77-5f7eef49beeb.png)

**Comment by kvichans** [comment]
I see a bug and a strangeness. 
Bug is simple. Fix.
About strangeness. What is output if you run in console

```
import os
=os.path.isdir('/')
```

**Comment by Alexey-T** [comment]
it shows True.

**Comment by kvichans** [comment]
Try version

**Comment by Alexey-T** [comment]
'no matches found' and stops.

**Comment by kvichans** [comment]
A-a-a! '/' was stripped to ''.
Fix
Try again

**Comment by Alexey-T** [comment]
fixd.
