### ISSUE TITLE
permiss err

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#50]
Got err in console.  

```
[57.59"]collect_files:1661 >>3(:)how_walk={'root': '/', 'sort_type': '', 'only_frst': 0, 'depth': -1, 'skip_binr': True, 'skip_hidn': True, 'file_excl': '', 'enco': ['cp1252', 'UTF-8', '<detected>'], 'file_incl': '*'}
[ 1'33.55"] collect_files:1732 |rsp|, stoped=(328, True)
[ 1'33.57"] 3(:)=[35.62"]
[ 1'33.60"]find_in_files:1525 ?? files (==[ 0.00"]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_find_in_files/__init__.py", line 4, in show_dlg
    def show_dlg(self, what='', opts={}):   return RLS.show_dlg(what, opts)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 113, in show_dlg
    return dlg_fif(what, opts)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 803, in dlg_fif
    ,progressor = progressor
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 1567, in find_in_files
    enco_s  = detect_encoding(path, detector)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 1410, in detect_encoding
    with open(path, 'rb') as h_path:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw1'
```

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
@Alexey-T Pls, test

**Comment by Alexey-T** [comment]
Still er
Esc to "stop piking"- "Picking stopped" and this error

**Comment by kvichans** [comment]
Repeate test, pls

**Comment by Alexey-T** [comment]
no "permis err". But now OS err
(Esc on pick stage)

```
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 1434, in detect_encoding
    with open(path, 'rb') as h_path:
OSError: [Errno 6] No such device or address: '/dev/log'
```

**Comment by kvichans** [comment]
у вас отключен "fif_log_file" ?

**Comment by kvichans** [comment]
включите `"fif_FNDLOG":true,` 
посмотрите в консоли последнюю строку с `find_in_files:1562 path_n, path=`
что там за хитрый файл?

**Comment by Alexey-T** [comment]
```
[ 8.15"]find_in_files:1562 path_n, path=(21, '/bin/zdiff')
[ 8.16"]find_in_files:1562 path_n, path=(22, '/bin/which')
[ 8.16"]find_in_files:1562 path_n, path=(23, '/dev/log')
```

**Comment by kvichans** [comment]
и? что это?

**Comment by Alexey-T** [comment]
/dev/log? файл размера 0. атр +r+w.

**Comment by kvichans** [comment]
можете в консоли его открыть open(path, 'rb') ?

**Comment by Alexey-T** [comment]
DblCmd не может его откр.

**Comment by kvichans** [comment]
мне отсюда не угадать почему это так

**Comment by Alexey-T** [comment]
можно ставить try-except.

**Comment by kvichans** [comment]
ладно - только лучше бы разобраться

**Comment by kvichans** [comment]
пробуйте

**Comment by Alexey-T** [comment]
теперь.
после esc picking: завис.
лог

```
[12.35"]find_in_files:1566 path_n, path=(23, '/dev/log')
[12.35"]find_in_files:1566 path_n, path=(24, '/dev/video0')
[12.44"]find_in_files:1566 path_n, path=(25, '/dev/kvm')
[12.44"]find_in_files:1566 path_n, path=(26, '/dev/sg1')
```

![ff](https://cloud.githubusercontent.com/assets/4154978/15274044/d12d3bd6-1aba-11e6-91e6-9104dc0b10ee.png)

**Comment by kvichans** [comment]
Что мне еще сделать?

**Comment by Alexey-T** [comment]
ясно. DCmd завис тоже. /dev/sg1
файл плох

**Comment by kvichans** [comment]
нужно найти различающий атрибут

**Comment by Alexey-T** [comment]
у него crw-rw- ("C"-?)

**Comment by kvichans** [comment]
первый раз такое вижу

**Comment by Alexey-T** [comment]
crw-rw-r--: a character special file. Про "c"

**Comment by kvichans** [comment]
теперь нужно в питоне найти способ выделения этого атрибута
а у /dev/log есть что-то особенное?

**Comment by Alexey-T** [comment]
да,
srw-rw-
"s"- ? (не нашел)
