### ISSUE TITLE
TypeError on nav for wrong line

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files#88]
Получил креш при навигации не по той строке
в

```
+Search for "Invertrect" in "/home/user/lazarus/lcl/interfaces" (7 matches in 4 files)
    </home/user/lazarus/lcl/interfaces/cocoa/cocoagdiobjects.pas>: #2
        <(406)>:     procedure InvertRectangle(X1, Y1, X2, Y2: Integer);
        <(1603)>: procedure TCocoaContext.InvertRectangle(X1, Y1, X2, Y2: Integer);
    </home/user/lazarus/lcl/interfaces/cocoa/cocoacaret.pas>: #1
        <(313)>:       FView.lclGetCallback.GetContext.InvertRectangle(FPos.X, FPos.Y,
    </home/user/lazarus/lcl/interfaces/carbon/carboncanvas.pp>: #3
        <(134)>:     procedure InvertRectangle(X1, Y1, X2, Y2: Integer);
        <(1197)>:   Method:  TCarbonDeviceContext.InvertRectangle
        <(1205)>: procedure TCarbonDeviceContext.InvertRectangle(X1, Y1, X2, Y2: Integer);
    </home/user/lazarus/lcl/interfaces/carbon/carboncaret.pas>: #1
        <(316)>:       (FWidget.Context as TCarbonDeviceContext).InvertRectangle(FPos.X, FPos.Y,
```

каретка стоит в 0:0, вызываем из конт-меню Goto definition,
==>

```
Python 3.4.3 (default, Oct 14 2015, 20:31:36) 
[GCC 4.8.4]
Setting icons: AwOken_24x24
[ 0.02"]collect_files:1088 >>1(:)how_walk={'file_excl': '', 'only_frst': 0, 'root': '/home/user/lazarus/lcl/interfaces', 'enco': ['cp1252', 'UTF-8', '<detected>'], 'skip_hidn': True, 'sort_type': '', 'depth': -1, 'file_incl': '*.pas *.inc *.pp', 'skip_binr': False, 'skip_unwr': False}
[ 0.74"]    collect_files:1173 |rsp|, stoped=(530, False)
[ 0.76"]    1(:)=[ 0.10"]
[ 0.78"]find_in_files:946 ?? files (==[ 0.00"] what_find={'find': 'Invertrect', 'word': False, 'case': False, 'mult': False, 'repl': None, 'reex': False}
[ 5.28"]find_in_files:1021 ok files ==)[ 4.50"] #rsp_i={'frgms': 7, 'brow_files': 530, 'find_stopped': False, 'cllc_files': 530, 'cllc_stopped': False, 'files': 4}
[ 5.31"]report_to_tab:103 (==[ 0.00"] |paths|=4
[ 5.98"]report_to_tab:406 ==)[ 0.68"] stoped=False
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_find_in_files/__init__.py", line 18, in on_goto_def
    def on_goto_def(self, ed_self):         return RLS.on_goto_def(ed_self)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 111, in on_goto_def
    self._nav_to_src('same', 'move')
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fi_in_fi.py", line 106, in _nav_to_src
    return nav_to_src(where, how_act)
  File "/home/user/.cudatext/py/cuda_find_in_files/cd_fif_api.py", line 692, in nav_to_src
    if os.path.isfile(path) or path.startswith('tab:'):
  File "/usr/lib/python3.4/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument
```

**Comment by kvichans** [comment]
ToDo
